/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.kotlin.mm


import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.boot.runApplication
import spring.kotlin.mm.controller.BlogProperties
import springfox.documentation.swagger2.annotations.EnableSwagger2


@SpringBootApplication(scanBasePackages = ["spring.kotlin.mm"])
@EnableConfigurationProperties(BlogProperties::class)
//@EnableSwagger2
class App

fun main(args: Array<String>) {
	runApplication<App>(*args)
}