/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.kotlin.mm


// import org.springdoc.core.configuration.SpringDocDataRestConfiguration
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.data.rest.RepositoryRestMvcAutoConfiguration
import org.springframework.boot.runApplication


// @SpringBootApplication(exclude = [RepositoryRestMvcAutoConfiguration::class])
@SpringBootApplication
class App


fun main(args: Array<String>) {
	runApplication<App>(*args)
}