/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.kotlin.mm


import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.domain.EntityScan
import org.springframework.boot.runApplication
import org.springframework.context.annotation.ComponentScan
import org.springframework.data.jpa.repository.config.EnableJpaRepositories


@SpringBootApplication
class App

fun main(args: Array<String>) {
	runApplication<App>(*args)
}