spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddl-auto: update
  swagger:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

  springdoc:
    paths-to-exclude: /swagger-resources/profile**
#  data:
#    rest:
#      detection-strategy: annotated
#  devtools:
#    livereload:
#      enabled: true
#    add-properties: false

#    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true

blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow.