spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddl-auto: update

  springdoc:
    paths-to-exclude: /productEntities/**
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  devtools:
    livereload:
      enabled: true
    add-properties: false
  hateoas:
    use-hal-as-default-json-media-type: false





